import Head from "next/head";
import { useState } from "react";
import { motion, LayoutGroup } from "framer-motion";

export default function Home() {
  const [toggle, isToggled] = useState(false);

  const handleToggle = () => {
    isToggled(!toggle);
  };

  // const variants = {
  //   front: { rotateY: 45 },
  //   back: { rotateY: 0 },
  // };
  // const spring = {
  //   type: "spring",
  //   stiffness: 700,
  //   damping: 30,
  //   transition: { duration: 0.3 },
  // };


  const variantOne = {
    on: {transform: 'translate3d(0, 0, -200rem) rotate3d(0, 1, 0, 60deg)'},
    off: {transform: 'translate3d(0, 0, 0rem) rotate3d(0, 1, 0, 0deg)'}
  }
  const variantTwo = {
    on: {transform: 'translate3d(0%, 0%, -100rem) rotate3d(0, 1, 0, 60deg)'},
    off: {transform: 'translate3d(0, 0, 0rem) rotate3d(0, 1, 0, 0deg)'}
  }
  const variantThree = {
    on: {transform: 'translate3d(0, 0, 0rem) rotate3d(0, 1, 0, 60deg)'},
    off: {transform: 'translate3d(0, 0, 0rem) rotate3d(0, 1, 0, 0deg)'}
  }
  const variantFour = {
    on: {transform: 'translate3d(250%, 0, -200rem) rotate3d(0, 1, 0, 120deg'},
    off: {transform: 'translate3d(0%, 0, 0rem) rotate3d(0, 1, 0, 0deg)'}
  }
  const variantFive = {
    on: {transform: 'translate3d(250%, 0, -100rem) rotate3d(0, 1, 0, 120deg)'},
    off: {transform: 'translate3d(0%, 0, 0rem) rotate3d(0, 1, 0, 0deg)'}
  }
  const variantSix = {
    on: {transform: 'translate3d(250%, 0, 0rem) rotate3d(0, 1, 0, 120deg)'},
    off: {transform: 'translate3d(0%, 0, 0rem) rotate3d(0, 1, 0, 0deg)'}
  }

  // const variantMain = {
  //   on: 
  //   off:
  // }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutGroup>
        <div className="container ">
        <motion.main
          layout
          transition={{ duration: 1.2 }}
          // style={{
          //   placeItems: toggle ? "center" : "revert",
          // }}
          className=" outer"
        >
          <motion.div
            layout
            variants={variantOne}
            initial="on"
            transition={{ duration: 1.2 }}
            onClick={handleToggle}
            className="cardy"
            animate={toggle ? 'on' : 'off'}
            // style={{
            //   transform: toggle ? 'translate3d(0, 0, -200rem) rotate3d(0, 1, 0, 60deg)' : 'translate3d(0, 0, -200rem) rotate3d(0, 1, 0, 0deg)'
            // }}
          ></motion.div>

          <motion.div
          variants={variantTwo}
            initial="on"
            transition={{ duration: 1.2 }}
            layout
            onClick={handleToggle}
            className="cardy"
            animate={toggle ? 'on' : 'off'}
          ></motion.div>

          <motion.div
          variants={variantThree}
            initial="on"
            transition={{ duration: 1.2 }}
            layout
            onClick={handleToggle}
            className="cardy"
            animate={toggle ? 'on' : 'off'}
          ></motion.div>

          <motion.div
          variants={variantFour}
            initial="on"
            transition={{ duration: 1.2 }}
            layout
            onClick={handleToggle}
            className="cardy"
            animate={toggle ? 'on' : 'off'}
          ></motion.div>

          <motion.div
          variants={variantFive}
            initial="on"
            transition={{ duration: 1.2 }}
            layout
            onClick={handleToggle}
            className="cardy"
            animate={toggle ? 'on' : 'off'}
          ></motion.div>

          <motion.div
          variants={variantSix}
            initial="on"
            transition={{ duration: 1.2 }}
            layout
            onClick={handleToggle}
            className="cardy"
            animate={toggle ? 'on' : 'off'}
          ></motion.div> 


        </motion.main>
        </div>
      </LayoutGroup>
      
    </div>
  );
}
